name: Firebase Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Write .env file
        run: echo "${{ secrets.ENV }}" > .env

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Setup Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Deploy to Firebase Dev
        run: |
          echo $GOOGLE_APPLICATION_CREDENTIALS > $RUNNER_TEMP/account.json
          export GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/account.json
          npm run deploy:ci:dev
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

  build-and-deploy-prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
    needs: build-and-deploy-dev
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Write .env file
        run: echo "${{ secrets.ENV }}" > .env

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Setup Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Deploy to Firebase Production
        run: |
          echo $GOOGLE_APPLICATION_CREDENTIALS > $RUNNER_TEMP/account.json
          export GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/account.json
          npm run deploy:ci:prd
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} 